name = "dnssec-offchain-gateway"
compatibility_date = "2022-06-20"
account_id = "de97cd2a1370a6ed2ad759f894179bff"
main = "./src/index.ts"
node_compat = true
kv_namespaces = [
    { binding = "OFFCHAIN_STORE_DEV", id = "eecc23992fe64d0ebd577896db6a94a4", preview_id = "eecc23992fe64d0ebd577896db6a94a4" }
]

[dev]
port = 8000

[build]
command = "yarn build"

[vars]
OG_DATA = "test.eth.json"
OG_TTL = "60"
